#!/bin/bash

# 🚀 LEVEL 3 QUICK REFERENCE
# Copy-paste these commands to use your system

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🔥 LEVEL 3: ENTERPRISE AI SYSTEM - QUICK START 🔥      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}STEP 1: Start Backend${NC}"
echo "cd /workspaces/ceo"
echo "uvicorn backend.server:app --reload"
echo ""

echo -e "${YELLOW}STEP 2: Test LEVEL 1 (Basic Product Creation)${NC}"
echo "curl -X POST http://localhost:8000/api/run"
echo ""

echo -e "${YELLOW}STEP 3: Check Results${NC}"
echo "curl http://localhost:8000/api/projects"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}LEVEL 2 COMMANDS (Monetization)${NC}"
echo ""
echo "Scale to 5 projects/day:"
echo "curl -X POST 'http://localhost:8000/api/v2/scale/configure?projects_per_day=5'"
echo ""
echo "Generate 6-month social calendar:"
echo "curl -X POST 'http://localhost:8000/api/v2/social/generate/{product_id}?days=180'"
echo ""
echo "Get revenue metrics:"
echo "curl http://localhost:8000/api/v2/revenue/all-metrics"
echo ""
echo "Get recommendations:"
echo "curl http://localhost:8000/api/v2/improve/recommendations"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}LEVEL 3 COMMANDS (Enterprise)${NC}"
echo ""
echo "Enable enterprise scaling (50+ projects/day):"
echo "curl -X POST 'http://localhost:8000/api/v3/enterprise/enable-scaling?projects_per_day=50&concurrent_workers=10'"
echo ""
echo "Get enterprise status:"
echo "curl http://localhost:8000/api/v3/enterprise/status"
echo ""
echo "Generate YouTube Shorts (30 scripts):"
echo "curl -X POST 'http://localhost:8000/api/v3/youtube/generate-shorts/{product_id}?days=30'"
echo ""
echo "Create email list:"
echo "curl -X POST 'http://localhost:8000/api/v3/email/create-list/{product_id}'"
echo ""
echo "Generate 30-day email sequence:"
echo "curl -X POST 'http://localhost:8000/api/v3/email/generate-sequence/{product_id}?days=30'"
echo ""
echo "Create AI support bot:"
echo "curl -X POST 'http://localhost:8000/api/v3/support/create-bot/{product_id}'"
echo ""
echo "A/B test prices:"
echo "curl -X POST 'http://localhost:8000/api/v3/analytics/ab-test/price/{product_id}?price_a=19.99&price_b=29.99'"
echo ""
echo "Analyze competitor:"
echo "curl 'http://localhost:8000/api/v3/competitors/analyze/CompetitorName'"
echo ""
echo "Run 50 projects in parallel:"
echo "curl -X POST 'http://localhost:8000/api/v3/enterprise/run-cycle/50'"
echo ""
echo "Get performance metrics:"
echo "curl 'http://localhost:8000/api/v3/enterprise/performance?days=7'"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${YELLOW}📊 EXPECTED RESULTS${NC}"
echo ""
echo "LEVEL 1: 20 projects/month"
echo "  → $1,000/month revenue"
echo ""
echo "LEVEL 2: 150 projects/month (5/day)"
echo "  → $225,000/month revenue"
echo ""
echo "LEVEL 3: 1,500 projects/month (50/day)"
echo "  → $2,250,000/month revenue"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}API DOCUMENTATION${NC}"
echo ""
echo "Swagger UI: http://localhost:8000/docs"
echo "ReDoc: http://localhost:8000/redoc"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}PROJECT STRUCTURE${NC}"
echo ""
echo "backend/"
echo "├── server.py (main app)"
echo "├── core/"
echo "│   ├── models.py (MongoDB)"
echo "│   ├── routes.py (LEVEL 1)"
echo "│   ├── routes_v2.py (LEVEL 2)"
echo "│   ├── routes_v3.py (LEVEL 3)"
echo "│   ├── autonomous_engine.py (LEVEL 1)"
echo "│   └── autonomous_engine_v2.py (LEVEL 2)"
echo "└── ai_services/"
echo "    ├── gumroad_publisher.py"
echo "    ├── social_media_scheduler.py"
echo "    ├── revenue_tracker.py"
echo "    ├── scaling_engine.py"
echo "    ├── self_improving_loop.py"
echo "    ├── youtube_shorts_automator.py"
echo "    ├── email_list_builder.py"
echo "    ├── customer_support_ai.py"
echo "    ├── advanced_analytics.py"
echo "    ├── competitor_analyzer.py"
echo "    └── enterprise_scaler.py"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${YELLOW}📚 DOCUMENTATION FILES${NC}"
echo ""
echo "DEPLOYMENT.md      - Render + Vercel setup"
echo "LEVEL2_DOCS.md     - Monetization guide"
echo "LEVEL3_DOCS.md     - Enterprise guide"
echo "SYSTEM_OVERVIEW.md - Complete system overview"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}🚀 YOU'RE READY!${NC}"
echo ""
echo "1. Start backend: uvicorn backend.server:app --reload"
echo "2. Visit: http://localhost:8000/docs"
echo "3. Try endpoints above"
echo "4. Monitor: http://localhost:8000/api/v3/enterprise/status"
echo ""

echo "════════════════════════════════════════════════════════════"
